title: Documentation JeeMate
description: La documentation de l'application mobile JeeMate for Jeedom
theme: just-the-docs

url: https://sagitaz.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
